# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: dmschulman.com
email: david@dmschulman.com
description: > # this means to ignore newlines until "baseurl:"
  My great website
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://dmschulman.com"

# Build settings
markdown: kramdown
theme: blanched
gems:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-rss
exclude:
  - Gemfile
  - Gemfile.lock

# add scope defaults for each content type
