# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: dmschulman.com
email: david@dmschulman.com
description: > # this means to ignore newlines until "baseurl:"
  My great website
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://dmschulman.com"

# Define collections
# collections_dir: content
collections:
  - photos
      output: true
      permalink: /photos/index.html
  # posts
    # output: true
    # permalink: /blog/index.html

# Build settings
markdown: kramdown
theme: apollo
gems:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-rss
exclude:
  - Gemfile
  - Gemfile.lock
