source 'https://rubygems.org'

gem 'github-pages'
gem 'jekyll-avatar'
gem 'jekyll-feed'
gem 'jekyll-paginate'
gem 'jekyll-seo-tag'
gem 'jekyll-sitemap'
gem 'jekyll-titles-from-headings'
gem 'jemoji'
gem 'nokogiri'
gem 'rouge'
gem 'ruby'
gem 'jekyll-target-blank'
